name: ThirdEye
main: com.te.Main
autor: FEST_Channel
version: 0.1.0
commands:
         te:
         ping:
         hat:
         top:
         fix:
         look:
         deldat:
         torch:
api-version: 1.15